### ISSUE TITLE
about feature extractor

### ISSUE THREAD

**Issue by Chuckie-He** [MVIG-SJTU/AlphAction#11]
Thank you for sharing! I want to get the person and object features after RoIAlign(save them to disk), but I don't know how to do. should I change part_forward equal to 0? can you give me some hints? thanks!

**Comment by yelantf** [comment]
Hi, thanks for your attention! You can simply modify the following line and then run inference to to do so.
https://github.com/MVIG-SJTU/AlphAction/blob/4b3b2737018701d6d1fb10e7f479cb4c00403446/AlphAction/engine/inference.py#L75

**Comment by Chuckie-He** [comment]
thanks a lot! I think it may help~
