### ISSUE TITLE
关于ava_train_det_person_bbox.json

### ISSUE THREAD

**Issue by Chuckie-He** [MVIG-SJTU/AlphAction#14]
作者你好，请问方便提供一下ava_train_det_person_bbox.json吗？请问这里的category_id是gt的动作类别还是0/1呢？

**Comment by yelantf** [comment]
你好，我们训练时直接使用了AVA数据集中的groundtruth box，并没有在训练集上检测人体框；在ava_val_det_person_bbox.json中，category_id指的是object类别，因为仅检测了人，所以均为1。

**Comment by yelantf** [comment]
Issue closed due to the lack of response.
