### ISSUE TITLE
为什么没看见AlphAction.custom_ext这个模块

### ISSUE THREAD

**Issue by ITPreson** [MVIG-SJTU/AlphAction#15]

**Comment by yelantf** [comment]
你好，这个模块是用CUDA代码编译生成的，需要按照 [INSTALL.md](https://github.com/MVIG-SJTU/AlphAction/blob/master/INSTALL.md) 中的指令安装才能导入。

https://github.com/MVIG-SJTU/AlphAction/blob/4b3b2737018701d6d1fb10e7f479cb4c00403446/setup.py#L80-L87
