### ISSUE TITLE
A Problem when running demo

### ISSUE THREAD

**Issue by Fishhao123** [MVIG-SJTU/AlphAction#16]
Hi, I met a problem when trying to run the demo.py, it seems that there is something missing. Could you please provide a solution?Thanks.

import AlphAction.custom_ext as _C
ModuleNotFoundError: No module named 'AlphAction.custom_ext'

**Comment by yelantf** [comment]
Did you successfully install this project? You should follow the steps shown in [INSTALL.md](https://github.com/MVIG-SJTU/AlphAction/blob/master/INSTALL.md) and ensure that no error occurs when running the command `python setup.py build develop`. Currently, this project does not support PyTorch 1.5+ and you should choose PyTorch 1.1.0-1.4.1. Also, as mentioned in #10 , you should check if you system nvcc version is the same as the one built with PyTorch.

**Comment by yelantf** [comment]
Issue closed due to the lack of response.
