### ISSUE TITLE
What are the selected common categories?

### ISSUE THREAD

**Issue by semchan** [MVIG-SJTU/AlphAction#17]
Great job. For the demo, may I know what are the selected common categories? thanks a lot
" We select 15 common categories from the 80 action categories of AVA, and provide a practical model which achieves high accuracy (about 70 mAP) on these categories."

**Comment by yelantf** [comment]
Of course, these common categories can be found in `demo/visualizer.py`, which are as follows.
https://github.com/MVIG-SJTU/AlphAction/blob/4b3b2737018701d6d1fb10e7f479cb4c00403446/demo/visualizer.py#L109-L125

Thanks for your attention!
