### ISSUE TITLE
how is the inference speed?

### ISSUE THREAD

**Issue by semchan** [MVIG-SJTU/AlphAction#18]
hi, I'm running the demo found that the speed is about 5 fps, is that correct? I'm runing the demo on RTX2070 ONE GPU card. thanks

113it [00:19,  4.20it/s]

**Comment by yelantf** [comment]
Hi, we did not experiment on the RTX2070. On our GPU RTX 2080 Ti, the speed is about 10 fps. Condisering that RTX 2080 Ti is more powerful, the speed on your machine should be reasonable.

**Comment by semchan** [comment]
> Hi, we did not experiment on the RTX2070. On our GPU RTX 2080 Ti, the speed is about 10 fps. Condisering that RTX 2080 Ti is more powerful, the speed on your machine should be reasonable.

thanks very much for your reply. I have one more question for the speed. I noted that there is a parameter of "--detect-rate" , is it an action detection interval number? If set this parameter higher, the speed should be faster, am I correct? but I found I set this parameter higher, it seems no change for the speed.

**Comment by yelantf** [comment]
The `detect-rate` is the rate at which we update the action labels. For example, when `detect-rate=4`, it means that in one second, the action labels of each person are updated four times. In each update, the model will use a short clip of 64 frames as input and predict the new action labels. To process a 64-frame clip, our ResNet-101 takes about 0.2 seconds (on RTX 2080 TI), which means `detect-rate>5` will takes more than one second to provide labels for a one-second clip. Thus, using higher `detect-rate` should slow down the speed.  

However, we also use a tracking model to track each actors. The speed of tracking model is about 10 fps, which is a bottleneck when `detect-rate` is low.

**Comment by semchan** [comment]
> The `detect-rate` is the rate at which we update the action labels. For example, when `detect-rate=4`, it means that in one second, the action labels of each person are updated four times. In each update, the model will use a short clip of 64 frames as input and predict the new action labels. To process a 64-frame clip, our ResNet-101 takes about 0.2 seconds (on RTX 2080 TI), which means `detect-rate>5` will takes more than one second to provide labels for a one-second clip. Thus, using higher `detect-rate` should slow down the speed.
> 
> However, we also use a tracking model to track each actors. The speed of tracking model is about 10 fps, which is a bottleneck when `detect-rate` is low.

Noted and thank you very much for your detailed explanation．If only this algorithm could be processed in real-time．

**Comment by yelantf** [comment]
Actually, if we use a low `detect-rate` with a realtime tracking method, this algorithm could be real-time. However, we did not find a robust realtime tracking method. Even the tracking model we use now is not very robust in the fast-motion scene. There is a tradeoff between speed and performance. Maybe in the future, a much stronger tracking method will make it possible.

**Comment by semchan** [comment]
> Actually, if we use a low `detect-rate` with a realtime tracking method, this algorithm could be real-time. However, we did not find a robust realtime tracking method. Even the tracking model we use now is not very robust in the fast-motion scene. There is a tradeoff between speed and performance. Maybe in the future, a much stronger tracking method will make it possible.

Noted with thanks. I will do some test based on your code to know more about your wonderful research
