### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by ITPreson** [MVIG-SJTU/AlphAction#19]
Thank you for sharing your amazing work.I would like to know if there is a specific release date for training code? I've been looking forward to it for a long time.

**Comment by yelantf** [comment]
Sorry for the long waiting. We were too busy to reformat and release the code before. We have release the training code and pre-trained model weights just now. Thanks for your attention!

**Comment by ITPreson** [comment]
It's worth the wait. Thank you very much for your work
