### ISSUE TITLE
No GPU?

### ISSUE THREAD

**Issue by amoldeshmukh18** [MVIG-SJTU/AlphAction#2]
Can this project run on low computing devices with no GPU? I want to run this on raspberry pi 4B, is it possible? What are the minimum system requirements and expected performance?

**Comment by yelantf** [comment]
Currently, this project does not support CPU inference. You can take a try to modify the codes by modifying each CUDA tensors or model parameters to CPU(Search "CUDA" and then you can get the relevant lines). About the system requirements, this codes originally requires a Linux server with Nvidia GPUs. To run the visual demo successfully, the memory size should not be small, 10GB+ is suggested.
