### ISSUE TITLE
real time test on video

### ISSUE THREAD

**Issue by semchan** [MVIG-SJTU/AlphAction#23]
Hi, the video processing time is not only depend on the parameters of "detect_rate", but also depend on the video size and the number of persons detected in the video. Would you please share me the video you tested? thanks a lot.

**Comment by yelantf** [comment]
Hello, you can try this video https://s3.amazonaws.com/ava-dataset/trainval/zG7mx8KiavA.mp4. It is also relevant to the resolution (aspect ratio) of the video.
