### ISSUE TITLE
A problem when run the demo.py

### ISSUE THREAD

**Issue by luckcodingdog** [MVIG-SJTU/AlphAction#27]
Hi,
Thanks a lot for your open source code, when i run the demo.py, i encounter a problem.

(alphaction) [zhuxt@localhost demo]$  python demo.py  --video-path "/home/zhuxt/workspace/actlyzer-app/exec/videos/10_persons_v2.mp4"  --output-path output.mp4 --cfg-path /home/zhuxt/workspace/AlphAction/config_files/resnet101_8x8f_denseserial.yaml --weight-path "/home/zhuxt/workspace/AlphAction-master/author_models/common_15cat_res101.pth" --common-cate
Starting video demo, video path: /home/zhuxt/workspace/actlyzer-app/exec/videos/10_persons_v2.mp4
Loading action model weight from /home/zhuxt/workspace/AlphAction-master/author_models/common_15cat_res101.pth.
Action model weight successfully loaded.
Loading YOLO model..
Network successfully loaded
Loading tracking model..
Network successfully loaded
Showing tracking progress bar (in fps). Other processes are running in the background.
Tracker Progress: 1624 frame [03:05,  7.75 frame/s]Process Process-4:
Traceback (most recent call last):
  File "/home/zhuxt/anaconda3/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zhuxt/anaconda3/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhuxt/workspace/AlphAction/demo/action_predictor.py", line 434, in _compute_prediction
    center_timestamp, video_size, ids = self.timestamps[timestamp_idx]
IndexError: list index out of range

As you can see from the log, it can run on the former frames, when it is 1624th frame, it is out of range.
I have test with several videos, it alse arise the same issue.

**Comment by yelantf** [comment]
Are you using the latest code? There was a bug in the demo program of previous versions, which I think was fixed five days ago.

Could you try `git pull origin master` in the project directory?

**Comment by luckcodingdog** [comment]
Thanks for your quick answer, it solved my question.
