### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by laomaup** [MVIG-SJTU/AlphAction#28]
Initialize according to file INSTALL.md.  when running the code 'pip install -e .' this is something error.
Installing collected packages: alphaction
  Attempting uninstall: alphaction
    Found existing installation: alphaction 0.0.0
    Can't uninstall 'alphaction'. No files were found to uninstall.
  Running setup.py develop for alphaction
    ERROR: Command errored out with exit status 1:
     command: /home/xianjin/anaconda3/envs/alphaction/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/action_recognition/AlphAction/setup.py'"'"'; __file__='"'"'/data/action_recognition/AlphAction/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /data/action_recognition/AlphAction/
    Complete output (107 lines):
    running develop
    running egg_info
    writing alphaction.egg-info/PKG-INFO
    writing dependency_links to alphaction.egg-info/dependency_links.txt
    writing requirements to alphaction.egg-info/requires.txt
    writing top-level names to alphaction.egg-info/top_level.txt
    reading manifest file 'alphaction.egg-info/SOURCES.txt'
    writing manifest file 'alphaction.egg-info/SOURCES.txt'
    running build_ext
    building 'alphaction._custom_cuda_ext' extension
    gcc -pthread -B /home/xianjin/anaconda3/envs/alphaction/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/data/action_recognition/AlphAction/alphaction/csrc -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/TH -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/xianjin/anaconda3/envs/alphaction/include/python3.7m -c /data/action_recognition/AlphAction/alphaction/csrc/vision.cpp -o build/temp.linux-x86_64-3.7/data/action_recognition/AlphAction/alphaction/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/data/action_recognition/AlphAction/alphaction/csrc -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/TH -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/xianjin/anaconda3/envs/alphaction/include/python3.7m -c /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu -o build/temp.linux-x86_64-3.7/data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    /home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
    
    /home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
    
    /home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
    
    /home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(128): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: a pointer to a bound function may only be used to call the function
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: type name is not allowed
    
    /data/action_recognition/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(173): error: expected an expression
    
    42 errors detected in the compilation of "/tmp/tmpxft_00004211_00000000-6_SigmoidFocalLoss_cuda.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    ----------------------------------------
  ERROR: Can't roll back alphaction; was not uninstalled
ERROR: Command errored out with exit status 1: /home/xianjin/anaconda3/envs/alphaction/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/action_recognition/AlphAction/setup.py'"'"'; __file__='"'"'/data/action_recognition/AlphAction/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by yelantf** [comment]
What is the output of `python -c 'from torch.utils.collect_env import main; main()`?

**Comment by laomaup** [comment]
>>> from torch.utils.collect_env import main
>>> main()
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Quadro 2000

Nvidia driver version: 384.111
cuDNN version: Probably one of the following:
/usr/local/lib/libcudnn.so.7
/usr/local/lib/libcunn.so.5

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py37_cu9.0.176_1    pytorch

**Comment by yelantf** [comment]
It seems related to pytorch's version. Could you try with a newer version of PyTorch (like 1.3.0 or even better 1.6.0)?

**Comment by laomaup** [comment]
ERROR: Command errored out with exit status 1:
     command: /home/xianjin/anaconda3/envs/alphaction/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/action_recognition/AlphAction/setup.py'"'"'; __file__='"'"'/data/action_recognition/AlphAction/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /data/action_recognition/AlphAction/
    Complete output (74 lines):
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running develop
    running egg_info
    writing alphaction.egg-info/PKG-INFO
    writing dependency_links to alphaction.egg-info/dependency_links.txt
    writing requirements to alphaction.egg-info/requires.txt
    writing top-level names to alphaction.egg-info/top_level.txt
    reading manifest file 'alphaction.egg-info/SOURCES.txt'
    writing manifest file 'alphaction.egg-info/SOURCES.txt'
    running build_ext
    building 'detector.nms.nms_cuda' extension
    gcc -pthread -B /home/xianjin/anaconda3/envs/alphaction/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/TH -I/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/xianjin/anaconda3/envs/alphaction/include/python3.7m -c detector/nms/src/nms_cuda.cpp -o build/temp.linux-x86_64-3.7/detector/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/action_recognition/AlphAction/setup.py", line 121, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 353, in build_extensions
        build_ext.build_extensions(self)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 269, in unix_wrap_compile
        "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 977, in _get_cuda_arch_flags
        capability = torch.cuda.get_device_capability()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/cuda/__init__.py", line 328, in get_device_capability
        prop = get_device_properties(device)
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/cuda/__init__.py", line 334, in get_device_properties
        init()  # will define _get_device_properties and _CudaDeviceProperties
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/cuda/__init__.py", line 164, in init
        _lazy_init()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
        _check_driver()
      File "/home/xianjin/anaconda3/envs/alphaction/lib/python3.7/site-packages/torch/cuda/__init__.py", line 111, in _check_driver
        of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
    AssertionError:
    The NVIDIA driver on your system is too old (found version 9000).
    Please update your GPU driver by downloading and installing a new
    version from the URL: http://www.nvidia.com/Download/index.aspx
    Alternatively, go to: https://pytorch.org to install
    a PyTorch version that has been compiled with your version
    of the CUDA driver.
    ----------------------------------------
  ERROR: Can't roll back alphaction; was not uninstalled
ERROR: Command errored out with exit status 1: /home/xianjin/anaconda3/envs/alphaction/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/action_recognition/AlphAction/setup.py'"'"'; __file__='"'"'/data/action_recognition/AlphAction/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by laomaup** [comment]
now pytorch's version is 1.3.0，but cuda‘s is 9.0.

**Comment by yelantf** [comment]
1. The system cuda version (shown by `nvcc --version`) should be the same as the version compiled with PyTorch. You may need to find a PyTorch package that compiled with CUDA9.0.
2. Or, you can upgrade your system CUDA to be the same as PyTorch requires. But in this way you will have to upgrade your nvidia driver also since your driver is too old to support newer CUDA version.

I would recommend you try the second option because it could be troublesome to install PyTorch1.3 for CUDA9.0. And the original bug seems also related to an old cuda version. Since nowadays deep learning framework are using CUDA[9.2, 10.1, 10.2] by default, I suggest installing [CUDA10.1](https://developer.nvidia.com/cuda-10.1-download-archive-update2) with a new enough NVIDIA driver(>=418.87).

**Comment by laomaup** [comment]
ok,i will try. thank you.

**Comment by laomaup** [comment]
a new problem
python demo.py --video-path ../test01.mp4 --output-path ../output --cfg-path ../config_files/resnet101_8x8f_baseline.yaml --weight-path ../data/models/aia_models/resnet101_8x8f_baseline.pth
Starting video demo, video path: ../test01.mp4
[ERROR:0] global /tmp/pip-req-build-yln3mf6z/opencv/modules/videoio/src/cap.cpp (561) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.4.0) /tmp/pip-req-build-yln3mf6z/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): ../output in function 'icvExtractPattern'

Loading action model weight from ../data/models/aia_models/resnet101_8x8f_baseline.pth.
Action model weight successfully loaded.
Loading tracking model..
Network successfully loaded
Showing tracking progress bar (in fps). Other processes are running in the background.
Tracker Progress: 123 frame [00:21,  5.66 frame/s]

this can't get the output video.

**Comment by yelantf** [comment]
Could you try setting the `--output-path` to be `../output.mp4`?

**Comment by laomaup** [comment]
it's work

**Comment by laomaup** [comment]
您好，上次与你们的论文作者联系过，说明了数据集不能下载的缘由，得到了回复。国内目前在google下载数据非常困难，麻烦您提供国内下载资源，例如百度网盘。谢谢您。



At 2020-10-27 12:49:50, "夜阑听风" <notifications@github.com> wrote:

Could you try setting the --output-path to be ../output.mp4?

**Comment by yelantf** [comment]
好的，我们有时间会尽快上传到百度网盘，百度云盘上传较慢，请耐心等待。

**Comment by laomaup** [comment]
ok，谢谢



在 2020-10-27 14:52:26，"夜阑听风" <notifications@github.com> 写道：

好的，我们有时间会尽快上传到百度网盘，百度云盘上传较慢，请耐心等待。

**Comment by yelantf** [comment]
dataset has been uploaded. 
link: https://pan.baidu.com/s/1UrflK4IgiVbVBOP5fDHdKA password:q5v5

**Comment by laomaup** [comment]
收到，谢谢



在 2020-10-27 22:32:52，"夜阑听风" <notifications@github.com> 写道：

dataset has been uploaded.
link: https://pan.baidu.com/s/1UrflK4IgiVbVBOP5fDHdKA password:q5v5
