### ISSUE TITLE
Too slow on test Stage 2

### ISSUE THREAD

**Issue by ZZZZZZZZJ** [MVIG-SJTU/AlphAction#3]
Thank you for sharing!

I try to run testing under the 'serial' configuration. But it seems quite slow on stage 2: almost over ten minutes for each batch. I'm confused about it.

I use 2 GPUs and set the VIDEOS_PER_BATCH 16.
 
I wonder whether the VIDEOS_PER_BATCH value is too big for me?  And does anything else influence the inference time?

**Comment by yelantf** [comment]
This is unusual. Stage 2 should be much faster than stage 1. One possible reason that I can think of now is insufficient CPU memory. If you run out of the CPU memory, the swap partition is then get used, which is usually much slower. What size of CPU memory are you using?

**Comment by yelantf** [comment]
Issue closed due to the lack of response.

**Comment by ZZZZZZZZJ** [comment]
Sorry to respond late. I found the slow running time is caused by too large dimensions of memory features. For each batch (batch size = 4), the memory feature is N* 305(61*5) * 2304 * 1 *1. Thus reducing the dimension and linear transformation of the memory features cost lots of time.
For example,
`mem_key = self.mem_dim_reduce(mem_key)`
