### ISSUE TITLE
when I run used video  it‘s not so good!!

### ISSUE THREAD

**Issue by Seiano** [MVIG-SJTU/AlphAction#30]
Hi! author, I run this demo but  It doesn't look as good as your demo！
1  I used  resnet101_8x8f_denseserial.yaml  and resnet101_8x8f_denseserial.pth.
2 When I used  common_15cat_res101.pth it's even worse.

so the reason it's the I have to pre-trained  that?  and  I want know your  demo's  picture size.

**Comment by yelantf** [comment]
You may need to adjust some hyper-parameters for better visualization effects (`--detect-rate`, `--visual-threshold`,  [`tracker_cfg`](../blob/master/detector/tracker_cfg.py), [`yolo_cfg`](../blob/master/detector/yolo_cfg.py)).

For the demo size, no matter what size the input video has, it will be resized to somewhat fixed size for computation. 
1. Each video is resized to have a 256 short side for action prediction
2. Each video is resized to be 1088x608 for person tracking.

**Comment by yelantf** [comment]
Issue closed due to the lack of response.
