### ISSUE TITLE
Question about the config files

### ISSUE THREAD

**Issue by xyang35** [MVIG-SJTU/AlphAction#32]
Hi, thanks again for sharing the great work. I'm running the training codes and found that the schedule in config files is slightly different from the one in the GETTING_STARTED page (https://github.com/MVIG-SJTU/AlphAction/blob/master/GETTING_STARTED.md#training). The setting of base learning and training iteration is not consistent (considering adjust schedule according to the linear scaling rule). I'm just wondering which version is correct for reproducing the result using the current codebase? Thanks!

**Comment by yelantf** [comment]
Just follow the config files. In GETTING_STARTED page, we take our AIA model config for example. In those config files, you can see that we train the baseline models with scheduler (50000, 70000, 90000), while our AIA models with scheduler (70000, 90000, 110000).

**Comment by xyang35** [comment]
Thanks for your reply! I can reproduce the results using the config files.
