### ISSUE TITLE
Fine-Tuning

### ISSUE THREAD

**Issue by harshsp31** [MVIG-SJTU/AlphAction#4]
Hi @Fang-Haoshu ,

Thank you for sharing your amazing work. I wanted to ask if you would be making a fine-tuning code available soon or not? It'll be really helpful for my project as well! Thanks

**Comment by yosagaf** [comment]
I'm looking for the fine-tuning code thanks for your amazing works

**Comment by yelantf** [comment]
@harshsp31 This project is not the same as AlphaPose, please check the author list before you open this issue. 

The fine-tuing code with pre-trained model will be released after ECCV, so stay tuned.
