### ISSUE TITLE
A question about 'ava_train_det_person_bbox.json'

### ISSUE THREAD

**Issue by lawkane** [MVIG-SJTU/AlphAction#40]
Hello, the author. I'm trying to train with a custom dataset.
I built my dataset as same as the AVA dataset directory structure. But as a rookie I am confused whether I need to replace the 'ava_train_det_person_bbox.json' ?
Thanks before for your reply.

**Comment by yelantf** [comment]
There is no "ava_train_det_person_bbox.json" in our pipeline because we train with the bounding boxes in the converted ground-truth annotation file "ava_train_v2.2_min.json". If you have done step 5 in [DATA.md](https://github.com/MVIG-SJTU/AlphAction/blob/master/DATA.md), this file should be generated.

However, according to your description, it seems that you are referring to "ava_val_det_person_bbox.json". Then the answer is, yes, you should replace those files listed in step6. 
For training, you should replace the "ava_train_det_object_bbox.json" by running the object detector on your custom dataset. For validation, you should run the human detector to replace "ava_val_det_person_bbox.json" and the object detector to replace "ava_val_det_object_bbox.json". The object JSON files are necessary for our IA structure.

**Comment by lawkane** [comment]
Thanks for your reply and sorry for my erroneous description.
Yes, I have done step 5 in DATA.md. Now I try to replace the files listed in step 6, but I can't find the guidance about running the detector to generate the new 'bbox.json'. Could you tell me how to run the object detector and human detector on my custom dataset?
Thanks again.

**Comment by lawkane** [comment]
@yelantf  
Thanks for your reply and sorry for my erroneous description.
Yes, I have done step 5 in DATA.md. Now I try to replace the files listed in step 6, but I can't find the guidance about running the detector to generate the new 'bbox.json'. Could you tell me how to run the object detector and human detector on my custom dataset?
Thanks again.

**Comment by yelantf** [comment]
We use `maskrcnn-benchmark` for detection tasks. The generated "ava_train_v2.2_min.json", "ava_val_v2.2_min.json" both have COCO format and could be used as their annotation files. Please refer to https://github.com/facebookresearch/maskrcnn-benchmark for detailed instructions.

**Comment by lawkane** [comment]
@yelantf 
Thank you very much for your answer. I will try to do this.

**Comment by lawkane** [comment]
@yelantf  Hi, the author.Now I have a new problem.
I prepared the dataset and run the command `python -m torch.distributed.launch --nproc_per_node=8 \ train_net.py --config-file "config_files/resnet50_4x16f_denseserial.yaml" \ --transfer --no-head --use-tfboard`
Then I got the error:

> 2020-12-01 22:20:13,839 alphaction.inference INFO: Start evaluation on ava_video_val_v2.2 dataset(0 videos).
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "train_net.py", line 245, in <module>
>     main()
>   File "train_net.py", line 235, in main
>     args.no_head)
>   File "train_net.py", line 98, in train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 134, in do_train
>     mem_active
>   File "/root/luohan/AlphAction/alphaction/engine/trainer.py", line 166, in val_in_train
>     mem_active,
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 170, in inference
>     predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 127, in compute_on_dataset
>     results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
>   File "/root/luohan/AlphAction/alphaction/engine/inference.py", line 53, in compute_on_dataset_2stage
>     loader_len = len(data_loader)
>   File "/root/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
>     return len(self._index_sampler)
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 107, in __len__
>     self._batches = self._prepare_batches()
>   File "/root/luohan/AlphAction/alphaction/dataset/samplers/grouped_batch_sampler.py", line 50, in _prepare_batches
>     order[sampled_ids] = torch.arange(len(sampled_ids))
> IndexError: tensors used as indices must be long, byte or bool tensors
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
>     main()
>   File "/root/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
>     cmd=cmd)
> subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train_net.py', '--local_rank=7', '--config-file', 'config_files/test.yaml', '--transfer', '--no-head', '--use-tfboard']' returned non-zero exit status 1.

I have made the "ava_val_v2.2.csv" and generated "ava_train_v2.2_min.json", "ava_val_v2.2_min.json".But it was unsuccessfully to start evaluation?
Thanks before for your reply.

**Comment by yelantf** [comment]
It shows that your dataset is empty, please ensure ava_val_v2.2_min.json is not empty and `ava_val_det_person_bbox.json` is correctly prepared.
> 2020-12-01 22:20:13,839 alphaction.inference INFO: Start evaluation on ava_video_val_v2.2 dataset(0 videos).

**Comment by lawkane** [comment]
@yelantf  I am sure that my "ava_val_v2.2_min.json" is not empty. I run the object detector and person detector on my dataset and got the "ava_val_det_person_bbox.json".The bounding box json is correctly prepared, but I still got the error. 
Besides, I tried to change the configure file that 
`DATASETS:
  TRAIN: ("ava_video_val_v2.2",)`
It was successful to run the train which show that my 'ava_val_v2.2_min.json' is not empty.
Now I am quite confused.

**Comment by yelantf** [comment]
So you can train with it but cannot do inference? The difference between training and inference is that during training we use the boxes in the annotation file, while during inference we use pre-computed bounding boxes. I think there may be some problem in your `ava_val_det_person_boxes` (for example, the img_id in it is not consistent with those in `ava_val_v2.2_min.json`). I think it should not be so hard to locate the problem, you can add some `print` in the dataset class to see why it becomes empty.

**Comment by lawkane** [comment]
@yelantf  Thanks for you advice. I add the `print` and found that during the function `make_data_loader`, the return 'data_loaders_val' is empty.Is 'ava_val_v2.2_min.json' relevant to the 'ava_video_val_v2.2.csv' when executed the make_data_loader?

**Comment by yelantf** [comment]
Yes, it is. I mean, you could add print in the dataset class defined in following lines. `json_dict` is the loaded json, `clip_ids` is the id numbers of every clip that will be used in the dataset. You can check when `clip_ids` gets empty with `print`.

https://github.com/MVIG-SJTU/AlphAction/blob/db19364dd2b15905ae4b70a7acd9bb9b34ccb04b/alphaction/dataset/datasets/ava.py#L64-L140

**Comment by lawkane** [comment]
@yelantf  Thank you very much. I check and found the img_id in `ava_val_det_person_boxes` is not consistent with those in `ava_val_v2.2_min.json`. That's what you said. Now the val video could be loaded.
Thanks again!
