### ISSUE TITLE
作者您好，拜读了您的作品，有几个问题想请教您。希望可以得到您的解答。

### ISSUE THREAD

**Issue by wen-flow** [MVIG-SJTU/AlphAction#44]
yolo 检测器和 Tracker 的模型文件是如何训练出来的啊， 我该如何训练自己的检测器和追踪模型呢？

**Comment by yelantf** [comment]
The model used in the demo program is simply imported from other programs, you could refer to the original repository for more information. For the training and inference, we use [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) to train the human detectors, you can refer to the final step in [DATA.md](https://github.com/MVIG-SJTU/AlphAction/blob/master/DATA.md) and maskrcnn-benchmark for more details. Besides, you may also interested in this issue https://github.com/MVIG-SJTU/AlphAction/issues/40 too.
