### ISSUE TITLE
Problem: Excessive graphics card memory usage

### ISSUE THREAD

**Issue by 13517592731** [MVIG-SJTU/AlphAction#45]
My operating environment: rtx3090, cuda11.0, pytorch1.7.1
When I run alphaction, my graphics card will use up to 8g of memory.
Is it possible to modify resnet101_8x8f_denseserial.yaml for optimization?
if possible, modify those configuration items will have an effect?

**Comment by yelantf** [comment]
This is expected behavior, since we have to use both tracking model and action detection model. You could try a lower resolution input for the tracking model, but this would lead to worse tracking performance.
