### ISSUE TITLE
How to track target people?

### ISSUE THREAD

**Issue by Tarmo-moriwaki** [MVIG-SJTU/AlphAction#46]
Hi,
thank you for providing very nice method.

I have one question about AIA. How to correspond one people in the frame and one people in next frame as same people?
This method seems to learn temporal information about each people in video. If you can, please tell me how to track people and where it is implemented.

**Comment by yelantf** [comment]
During training and inference, we do not track people frame by frame. Instead, we simply use the human boxes in the middle frame. In our demo program, for better visualization effects, we add a tracker model to track each person. You could refer to [this reply](https://github.com/MVIG-SJTU/AlphAction/issues/38#issuecomment-730962145) for more information.

**Comment by jun0wanan** [comment]
> Hi,
> thank you for providing very nice method.
> 
> I have one question about AIA. How to correspond one people in the frame and one people in next frame as same people?
> This method seems to learn temporal information about each people in video. If you can, please tell me how to track people and where it is implemented.

hi,
sorry to disturb you , I want to ask how the 1th clip's person bbox link to 2rd clip's person bbox (the same person)?

best,
jun
