### ISSUE TITLE
cuda error?

### ISSUE THREAD

**Issue by dfgan** [MVIG-SJTU/AlphAction#5]
"cuda runtime error(48):no kernel image is available for execution on the device at ./alphaction/csrc/cuda/ROIAlign3d_cuda.cu:300"
Please explain how to solve this error, thanks.

**Comment by yosagaf** [comment]
I have encounter this error while trying to install AlphAction, you may have compile AlphAction with a cpu version of pytorch. Check if you installed a cuda 10.1 version of Pytorch.

**Comment by yelantf** [comment]
@dfgan Please follow the installation instruction in INSTALL.md. Currently, this project does not support Pytorch version 1.5+.

**Comment by yelantf** [comment]
Issue closed due to the lack of response.
