### ISSUE TITLE
An error occurred during operation

### ISSUE THREAD

**Issue by melon-coder** [MVIG-SJTU/AlphAction#54]
from .roi_align_3d import ROIAlign3d
  File "/home/rbw/src/install_package/AlphAction/alphaction/layers/roi_align_3d.py", line 7, in <module>
    import alphaction._custom_cuda_ext as _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

Hello, I have installed the dependencies according to the requirements in "INSTALL.md", and the installation was successful at the end. However, when I run "demo.py", the above error occurred. What is the reason? Do you have any ideas to solve this problem?

**Comment by melon-coder** [comment]
The problem has been resolved 

[https://github.com/pytorch/pytorch/issues/38090#issue-614423025]

**Comment by fengjingchehu** [comment]
i wonder how did u solve such question ?

**Comment by melon-coder** [comment]
> i wonder how did u solve such question ?

Sorry, it is too long ago and I can't remember it. You can review the wrong information again. If it still can't be solved, I suggest you submit issues again

**Comment by fengjingchehu** [comment]
Thank you for your reply
