### ISSUE TITLE
failed to Install

### ISSUE THREAD

**Issue by huwolong** [MVIG-SJTU/AlphAction#6]
the follow is the error message when type python setup.py build develop.
detector/nms/src/nms_cuda.cpp:4:80: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                                                                ^
detector/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^
error: command 'gcc' failed with exit status 1

**Comment by huwolong** [comment]
i just solved this proplem by uninstalling torch==1.5.1 and installing torch==1.3.1

**Comment by yelantf** [comment]
@huwolong Thanks for openning this issue. Currently, PyTorch 1.5+ is not supported since AT_CHECK is deprecated(https://github.com/open-mmlab/mmdetection/issues/2513). We will fix this in the next update. For now, please use PyTorch 1.0-1.4

**Comment by yelantf** [comment]
This issue is fixed in the latest update bcb6b16ba4db8ce23428f3ca96b9130fe6397d02.
