### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by irvingzhang0512** [MVIG-SJTU/AlphAction#63]
Hi @yelantf , Thanks for your work! It's really helpful.

I have a question about the licence since there is no licence for this repo. Your visualization tool (color scheme) is very awesome and I wonder if I can borrow this visualization tool to open-mmlab/mmaction2#795

**Comment by yelantf** [comment]
Hi, thanks for your interest in this project! For now, it is free to reuse this project for non-commercial use. Will let you know if there are more restrictions in the future.
