### ISSUE TITLE
训练代码

### ISSUE THREAD

**Issue by yangkang779** [MVIG-SJTU/AlphAction#7]
非常好的工作，请问作者什么时候开源训练代码呢？

**Comment by yelantf** [comment]
Thanks for your attention! The training code with pre-trained model will be released after ECCV, please stay tuned.

**Comment by yangkang779** [comment]
Eccv的论文结果已经出来了，可以提前公布学习学习么？这个疫情导致会议应该会拖到很晚哎，谢谢啊
