### ISSUE TITLE
key frames

### ISSUE THREAD

**Issue by yan-ctrl** [MVIG-SJTU/AlphAction#86]
Could you please share the key frames again? Only the clips video, but no key frames.

**Comment by yelantf** [comment]
link: https://pan.baidu.com/s/1Wv5px_e8vFiYI4K9icb6uw code: l94c

**Comment by yan-ctrl** [comment]
> link: https://pan.baidu.com/s/1Wv5px_e8vFiYI4K9icb6uw code: l94c

Thank you for your link. It's very helpful. Have I seen you in CSDN?

**Comment by yelantf** [comment]
The one you saw in CSDN should not be me because I did not use it much.  lol

**Comment by yan-ctrl** [comment]
OK, ID is familiar.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MVIG-SJTU/AlphAction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 晚上11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphAction] key frames (Issue #86)





 
The one you saw in CSDN should not be me because I did not use it much.  lol
